### ISSUE TITLE
Upload release latest build again

### ISSUE THREAD

**Issue by odil24** [TheoBaudoinLighting/Horus-Vision#1]
It seems like release files not fully uploaded. ucrtbased.dll has been missed

**Comment by TheoBaudoinLighting** [comment]
Hello, thank you for telling me, I'm planning to do a major upgrade on Monday with a direct installer and all the necessary dependencies up and running.

**Comment by odil24** [comment]
> Hello, thank you for telling me, I'm planning to do a major upgrade on Monday with a direct installer and all the necessary dependencies up and running.

I think for more portable using not need to make installer version instead zip portable.

**Comment by TheoBaudoinLighting** [comment]
You were right, and based on that, I've released a new portable version of Horus Vision `1.3`. It's now available for download.

**Comment by odil24** [comment]
@TheoBaudoinLighting Thanks for quick feedback but it has some missed files I guess:
![1116](https://github.com/TheoBaudoinLighting/Horus-Vision/assets/64298012/c7492753-b71c-484d-ab95-54b9525b2407)

**Comment by TheoBaudoinLighting** [comment]
![image](https://github.com/TheoBaudoinLighting/Horus-Vision/assets/30130580/0adf28cf-804a-45f4-90fb-ed0d92f5b927)

Looks like you've hit a `ucrtbased.dll` snag. Just to set things straight, this isn't tied to our engine's codebase; it's part of the Windows OS runtime environment — specifically the debug version of the Universal C Runtime, which typically crops up in a dev setting.

If you're running this in a non-dev environment, you might want to check that you're using the release version of your application. However, if this is dev-related, a quick `sfc /scannow` in an elevated CMD could root out any corrupted system files that might be muddying the waters.

And, of course, keep your system on its toes with the latest Windows updates. If all else fails, a repair or a fresh install of the Visual C++ Redistributable might be the play.

**Comment by TheoBaudoinLighting** [comment]
![2024-02-04 01_42_34-](https://github.com/TheoBaudoinLighting/Horus-Vision/assets/30130580/75c10594-6902-4f53-8410-18eefdcedcd0)

I've recently conducted a thorough test of HorusVision across three distinct systems to iron out any startup issues. The first rig was a Windows desktop powered by an i9-11900KF, 80GB of RAM, and dual GPUs - a GeForce RTX 3060 alongside a GTX 1080. The second was a laptop running Windows with an i7-11800H, 64GB of RAM, and a GeForce RTX 2080. The third setup was a Windows PC with an i3-8100, 64GB of RAM, and a single RTX 3060.

From these tests, the consistent startup bug identified was related to the number of GPUs present. I've addressed this in the latest engine update(i have updated the release), ensuring smoother operation across varying hardware configurations. There were no startup issues connected to the ucrtbased.dll file.

**Comment by odil24** [comment]
but i have that file on my system32 folder

**Comment by TheoBaudoinLighting** [comment]
![image](https://github.com/TheoBaudoinLighting/Horus-Vision/assets/30130580/447be0ea-8af3-47b0-a778-935aa9a27baf)

Noticed you found **ucrtbased.dll** in your System32, which is great news. Despite that, if you're still running into issues, there are a few things you can try on your own to get everything running smoothly.

First, check if the folder containing ucrtbased.dll is in your system's PATH. This step helps your PC know where to find this file when it's needed.

Giving the app admin rights could also make a difference. It often helps get past any permissions issues blocking access to the DLL.

You might not typically need to do this, but registering ucrtbased.dll manually could help. Just open an elevated command prompt and run regsvr32 **ucrtbased.dll**. It's a bit old school, but worth a shot.

Also, ensure you've got the right Visual C++ Redistributable package installed. Since **ucrtbased.dll** comes with Visual Studio 2015, reinstalling it might fix any issues.

Running a system file check with sfc /scannow from an admin command prompt is another good move. It can identify and fix corrupted system files, potentially solving your DLL problem.

If these steps don't sort it out, it might be necessary to dive deeper into the app's dependencies or the development environment's documentation for any specific guidance related to ucrtbased.dll.
